---
shortname: coq-itree-io
opam_name: coq-itree-io
organization: Lysxia
circleci: true
synopsis: Run interaction trees in IO
description: Interpret itree in the IO monad of simple-io.
authors:
  - name: Li-yao Xia
    email: lysxia@gmail.com
license:
  identifier: MIT
dependencies:
  - opam:
      name: coq-itree
      version: '{ >= "3.2.0" }'
  - opam:
      name: coq-simple-io
      version: '{ >= "1.3.0" }'
namespace: ITreeIO
opam-file-maintainer: 'Yishuai Li <yishuai@upenn.edu>'
tested_coq_opam_versions:
  - version: 'dev'
  - version: '8.12'
  - version: '8.11'
  - version: '8.10'
  - version: '8.9'
  - version: '8.8'
