---
shortname: coq-itree-io
opam_name: coq-itree-io
organization: Lysxia
action: true
ci_test_dependants: true
synopsis: Run interaction trees in IO
description: Interpret itree in the IO monad of simple-io.
authors:
  - name: Li-yao Xia
    email: lysxia@gmail.com
license:
  identifier: MIT
dependencies:
  - opam:
      name: coq-itree
      version: '{ >= "3.2.0" }'
  - opam:
      name: coq-simple-io
      version: '{ >= "1.3.0" }'
namespace: ITreeIO
opam-file-maintainer: 'Yishuai Li <liyishuai.lys@alibaba-inc.com>'
tested_coq_opam_versions:
  - version: 'dev'
  - version: '8.17'
  - version: '8.16'
  - version: '8.15'
  - version: '8.14'
  - version: '8.13'
  - version: '8.12'
supported_coq_versions:
  opam: '{ >= "8.12" }'
  test: '8.12 or later'
