version: 2.1

jobs:
  build:
    parameters:
      coq:
        type: string
    docker:
    - image: <<parameters.coq>>
    resource_class: medium
    environment:
      OPAMJOBS: 2
      OPAMVERBOSE: 1
      OPAMYES: true
      TERM: xterm
    steps:
    - checkout
    - run:
        name: Configure environment
        command: echo . ~/.profile >> $BASH_ENV
    - run:
        name: Install dependencies
        command: |
          opam update
          opam install --deps-only .
    - run:
        name: List installed packages
        command: opam list
    - run:
        name: Build, test, and install package
        command: opam install -t .
    - run:
        name: Uninstall package
        command: opam uninstall .

workflows:
  version: 2
  test:
    jobs:
    - build:
        name: "Coq dev"
        coq: "coqorg/coq:dev"
    - build:
        name: "Coq 8.12"
        coq: "coqorg/coq:8.12"
    - build:
        name: "Coq 8.11"
        coq: "coqorg/coq:8.11"
    - build:
        name: "Coq 8.10"
        coq: "coqorg/coq:8.10"
    - build:
        name: "Coq 8.9"
        coq: "coqorg/coq:8.9"
    - build:
        name: "Coq 8.8"
        coq: "coqorg/coq:8.8"
